[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number.
vt = next

# The default session, also known as the greeter.
[default_session]
command= "tuigreet -t --remember --remember-user-session --theme 'border=cyan;text=white;prompt=cyan;time=white;action=white;button=cyan;container=black;input=cyan'"
user = "greeter"