#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration
bold_font                   auto
bold_italic_font            auto
confirm_os_window_close     0
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
cursor_trail                1
dynamic_background_opacity  yes
enable_audio_bell           no
font_family                 Source Code Pro
font_size                   12
hide_window_decorations     yes
initial_window_height       500
initial_window_width        950
italic_font                 auto
remember_window_size        no
scrollback_lines            2000
selection_background        none
selection_foreground        none
wheel_scroll_min_lines      1
window_padding_width        10

# Include wallpaper colors
include colors.conf
