background = rgb({{background | strip}})

text = rgb({{foreground | strip}})

base = rgb({{color0 | strip}})

alternate_base = rgb({{color1 | strip}})

bright_text = rgb({{color8 | strip}})

accent = rgb({{color9 | strip}})

accent_secondary = rgb({{color10 | strip}})
