;;; doom-wallust-light-theme.el --- Wallust light theme for Doom -*- lexical-binding: t; no-byte-compile: t; -*-
;;
;; Author: Generated by doom-wallust
;; Source: Wallust - https://codeberg.org/explosion-mental/wallust
;;
;;; Commentary:
;; Auto-generated light theme based on wallust colors.
;;
;; Using this theme requires either Doom Emacs or using the doom-themes Emacs package in vanilla Emacs.
;;
;; To install, add this to your wallust templates section:
;; doom-wallust-dark = { template = 'doom-wallust-dark-theme.el', target = '/home/gabriel/.emacs.d/themes/doom-wallust-dark-theme.el' }
;;
;; 
;; You must also copy this template file to your $EMACS_DIR or $DOOM_DIR custom themes directory so that Wallust can replace it. If in vanilla emacs, you can set it like this:
;; (add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
;;; Code:

(require 'doom-themes)

;;
;;; Variables

(defgroup doom-wallust-light-theme nil
  "Options for the `doom-wallust-light' theme."
  :group 'doom-themes)

(defcustom doom-wallust-light-brighter-modeline nil
  "If non-nil, more vivid colors will be used to style the mode-line."
  :group 'doom-wallust-light-theme
  :type 'boolean)

(defcustom doom-wallust-light-brighter-comments nil
  "If non-nil, comments will be highlighted in more vivid colors."
  :group 'doom-wallust-light-theme
  :type 'boolean)

(defcustom doom-wallust-light-comment-bg doom-wallust-light-brighter-comments
  "If non-nil, comments will have a subtle highlight to enhance their legibility."
  :group 'doom-wallust-light-theme
  :type 'boolean)

(defcustom doom-wallust-light-padded-modeline doom-themes-padded-modeline
  "If non-nil, adds a 4px padding to the mode-line.
Can be an integer to determine the exact padding."
  :group 'doom-wallust-light-theme
  :type '(choice integer boolean))

;;
;;; Theme definition

(def-doom-theme doom-wallust-light
    "A light theme generated by wallust."
  :family 'doom-wallust
  :background-mode 'light

  ;; name        default   256       16
  ((bg         '("{{background}}" nil       nil))
   (fg         '("{{foreground}}" nil       nil))

   ;; Alternatives for solaire-mode - slightly darker than bg for light theme
   (bg-alt     (doom-darken '("{{background}}") 0.05))
   (fg-alt     '("{{color7}}" nil       nil))

   ;; Base colors - spectrum from bg to fg (inverted from dark theme)
   (base0      '("{{color15}}" nil "white"))
   (base1      (doom-darken bg 0.02))
   (base2      (doom-darken bg 0.05))
   (base3      (doom-darken bg 0.08))
   (base4      (doom-darken bg 0.15))
   (base5      (doom-darken bg 0.25))
   (base6      (doom-darken bg 0.35))
   (base7      (doom-darken fg 0.1))
   (base8      '("{{color0}}" nil "black"))

   (grey       base5)
   (red        '("{{color1}}" nil "red"))
   (orange     '("{{color9}}" nil "brightred"))
   (green      '("{{color2}}" nil "green"))
   (teal       '("{{color6}}" nil "brightgreen"))
   (yellow     '("{{color3}}" nil "yellow"))
   (blue       '("{{color4}}" nil "brightblue"))
   (dark-blue  (doom-darken blue 0.3))
   (magenta    '("{{color5}}" nil "magenta"))
   (violet     '("{{color13}}" nil "brightmagenta"))
   (cyan       '("{{color14}}" nil "brightcyan"))
   (dark-cyan  '("{{color6}}" nil "cyan"))

   ;; Face categories
   (highlight      blue)
   (vertical-bar   (doom-lighten base1 0.2))
   (selection      (doom-lighten blue 0.7))
   (builtin        (doom-darken magenta 0.2))
   (comments       (if doom-wallust-light-brighter-comments 
                       (doom-darken teal 0.2)
                     (doom-lighten fg 0.4)))
   (doc-comments   (doom-darken comments 0.15))
   (constants      (doom-darken violet 0.2))
   (functions      (doom-darken magenta 0.2))
   (keywords       (doom-darken blue 0.2))
   (methods        (doom-darken cyan 0.2))
   (operators      (doom-darken blue 0.2))
   (type           (doom-darken yellow 0.3))
   (strings        (doom-darken green 0.2))
   (variables      (doom-darken magenta 0.1))
   (numbers        (doom-darken orange 0.2))
   (region         (doom-darken bg-alt 0.15))
   (error          (doom-darken red 0.2))
   (warning        (doom-darken yellow 0.3))
   (success        (doom-darken green 0.2))
   (vc-modified    (doom-darken orange 0.2))
   (vc-added       (doom-darken green 0.2))
   (vc-deleted     (doom-darken red 0.2))

   ;; Custom categories
   (modeline-fg              fg)
   (modeline-fg-alt          base5)
   (modeline-bg              (if doom-wallust-light-brighter-modeline
                                 (doom-lighten blue 0.45)
                               (doom-lighten bg-alt 0.1)))
   (modeline-bg-alt          (if doom-wallust-light-brighter-modeline
                                 (doom-lighten blue 0.475)
                               (doom-lighten bg-alt 0.15)))
   (modeline-bg-inactive     (doom-lighten bg 0.1))
   (modeline-bg-inactive-alt (doom-lighten bg 0.15))

   (-modeline-pad
    (when doom-wallust-light-padded-modeline
      (if (integerp doom-wallust-light-padded-modeline) 
          doom-wallust-light-padded-modeline 
        4))))

  ;;;; Base theme face overrides
  (((line-number &override) :foreground base4)
   ((line-number-current-line &override) :foreground fg)
   ((font-lock-comment-face &override)
    :background (if doom-wallust-light-comment-bg (doom-darken bg 0.05) 'unspecified))
   (mode-line
    :background modeline-bg :foreground modeline-fg
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg)))
   (mode-line-inactive
    :background modeline-bg-inactive :foreground modeline-fg-alt
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-inactive)))
   (mode-line-emphasis :foreground (if doom-wallust-light-brighter-modeline base8 highlight))
   
   (hl-line :background (doom-darken bg 0.05))
   (region :background region :foreground nil :distant-foreground fg)

   ;;;; css-mode <built-in> / scss-mode
   (css-proprietary-property :foreground orange)
   (css-property             :foreground green)
   (css-selector             :foreground blue)
   ;;;; doom-modeline
   (doom-modeline-bar :background (if doom-wallust-light-brighter-modeline modeline-bg highlight))
   (doom-modeline-buffer-file :inherit 'mode-line-buffer-id :weight 'bold)
   (doom-modeline-buffer-path :inherit 'mode-line-emphasis :weight 'bold)
   (doom-modeline-buffer-project-root :foreground green :weight 'bold)
   ;;;; elscreen
   (elscreen-tab-other-screen-face :background base2 :foreground base0)
   ;;;; highlight-symbol
   (highlight-symbol-face :background (doom-darken base4 0.1) :distant-foreground fg-alt)
   ;;;; highlight-thing
   (highlight-thing :background (doom-darken base4 0.1) :distant-foreground fg-alt)
   ;;;; ivy
   (ivy-current-match :background selection :distant-foreground base0 :weight 'normal)
   ;;;; LaTeX-mode
   (font-latex-math-face :foreground green)
   ;;;; markdown-mode
   (markdown-markup-face :foreground base5)
   (markdown-header-face :inherit 'bold :foreground red)
   ((markdown-code-face &override) :background (doom-darken base3 0.05))
   ;;;; org <built-in>
   (org-hide :foreground bg)
   (org-block :background bg)
   (org-block-begin-line :foreground comments :background (doom-darken bg 0.04))
   ;;;; rjsx-mode
   (rjsx-tag :foreground red)
   (rjsx-attr :foreground orange)
   ;;;; solaire-mode
   (solaire-mode-line-face
    :inherit 'mode-line
    :background modeline-bg-alt
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-alt)))
   (solaire-mode-line-inactive-face
    :inherit 'mode-line-inactive
    :background modeline-bg-inactive-alt
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-inactive-alt)))
   ;;;; vimish-fold
   ((vimish-fold-overlay &override) :inherit 'font-lock-comment-face :background base3 :weight 'light)
   ((vimish-fold-fringe &override)  :foreground teal))

  ;;;; Base theme variable overrides
  ())

;;; doom-wallust-light-theme.el ends here
