[config]
contrast = 1.0

[templates.foot]
input_path  = '~/.config/matugen/templates/foot.ini'
output_path = '~/.config/foot/colors.ini'

[templates.emacs]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.emacs.d/colors.css'

[templates.hyprland]
input_path  = '~/.config/matugen/templates/hyprland.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'

[templates.wlogout]
input_path = '~/.config/matugen/templates/wlogout.css'
output_path = '~/.config/wlogout/style.css'

[templates.gtk3]
input_path  = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

[templates.gtk4]
input_path  = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

# [templates.qt5ct]
# input_path  = '~/.config/matugen/templates/qt.css'
# output_path = '~/.config/qt5ct/colors/matugen.conf'

# [templates.qt6ct]
# input_path  = '~/.config/matugen/templates/qt.css'
# output_path = '~/.config/qt6vt/colors/matugen.conf'
