# Primary colors are used for the most important elements, like a
# starred message and FAB to start a new message

# Tertiary colors are used for smaller emphasized elements, like a
# badge suggesting a follow up

# Secondary colors are used for less urgent elements, like the
# background of an inactive star icon and the selection state of an
# inbox icon

# Surface – A role used for backgrounds and large, low-emphasis areas
# of the screen.

# Primary, Secondary, Tertiary – Accent color roles used to emphasize
# or de-emphasize foreground elements.

# Container – Roles used as a fill color for foreground elements like
# buttons. They should not be used for text or icons.

# On – Roles starting with this term indicate a color for text or
# icons on top of its paired parent color. For example, on primary is
# used for text and icons against the primary fill color.

# Variant – Roles ending with this term offer a lower emphasis
# alternative to its non-variant pair. For example, outline variant is
# a less emphasized version of the outline color.

[config]
contrast = 1.0

[templates.foot]
input_path  = '~/.config/matugen/templates/foot.ini'
output_path = '~/.config/foot/colors.ini'

[templates.emacs]
input_path = '~/.config/matugen/templates/emacs.el'
output_path = '~/.emacs.d/themes/matugen-theme.el'

#[templates.hyprland]
#input_path  = '~/.config/matugen/templates/hyprland.lua'
#output_path = '~/.config/hypr/colors.lua'

[templates.niri]
input_path = '~/.config/matugen/templates/niri.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.wlogout]
input_path = '~/.config/matugen/templates/wlogout.css'
output_path = '~/.config/wlogout/style.css'

[templates.gtk3]
input_path  = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

[templates.gtk4]
input_path  = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.qt5ct]
input_path  = '~/.config/matugen/templates/qt.css'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path  = '~/.config/matugen/templates/qt.css'
output_path = '~/.config/qt6vt/colors/matugen.conf'
