[colors-dark]
alpha = 0.75
background=1F2224
foreground=DAF9F8

# Normal/regular colors (color palette 0-7)
regular0=494E4F  # black
regular1=435257  # red
regular2=4E696E  # green
regular3=607F81  # yellow
regular4=65959F  # blue
regular5=2A98A6  # magenta
regular6=70B2B0  # cyan
regular7=C2EEEC  # white

# Bright colors (color palette 8-15)
bright0=87A6A5   # bright black
bright1=465B61   # bright red
bright2=55787F   # bright green
bright3=659093   # bright yellow
bright4=4A9EAF   # bright blue
bright5=38CBDD   # bright magenta
bright6=95EDEA   # bright cyan
bright7=C2EEEC   # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>
