[colors-dark]
alpha = 0.75
background=141317
foreground=EDF1E4

# Normal/regular colors (color palette 0-7)
regular0=3E3D43  # black
regular1=6C6459  # red
regular2=4F6C77  # green
regular3=947B4D  # yellow
regular4=5F8772  # blue
regular5=4B8B94  # magenta
regular6=98A286  # cyan
regular7=DDE3D0  # white

# Bright colors (color palette 8-15)
bright0=9A9F92   # bright black
bright1=7D7263   # bright red
bright2=567D8B   # bright green
bright3=A1772D   # bright yellow
bright4=4E906D   # bright blue
bright5=2D95A6   # bright magenta
bright6=CBD8B2   # bright cyan
bright7=DDE3D0   # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>
