[colors-dark]
blur=true
alpha = 0.75
background=111416
foreground=C6F7F5

# Normal/regular colors (color palette 0-7)
regular0=3B3E42  # black
regular1=3C4851  # red
regular2=466778  # green
regular3=637B7F  # yellow
regular4=49869C  # blue
regular5=48868F  # magenta
regular6=45AEAA  # cyan
regular7=A5EBE9  # white

# Bright colors (color palette 8-15)
bright0=74A5A3   # bright black
bright1=3D4C59   # bright red
bright2=4A778D   # bright green
bright3=62858A   # bright yellow
bright4=298DB2   # bright blue
bright5=52ABB7   # bright magenta
bright6=5CE8E3   # bright cyan
bright7=A5EBE9   # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>
