alpha = 90

# How the image is parse, in order to get the colors:
# full
# resized
# wal
# thumb
# fastresize
# kmeans

backend = "wal"

# What color space to use to produce and select the most prominent colors:
# lab
# labmixed
# lch
# lchmixed
# labansi
# lchansi

color_space = "lch"

# Pallete:
#    ansidark
#    dark
#    harddark
#    light
#    softdark
#    softlight
# Variations (can be applied to all but ansidark):
#    16
#    comp (cannot be applied to ansidark)
#    comp16 (cannot be applied to ansidark)

palette = "softdark16"

# Difference between similar colors, used by the colorspace:
#  1          Not perceptible by human eyes.
#  1 - 2      Perceptible through close observation.
#  2 - 10     Perceptible at a glance.
#  11 - 49    Colors are more similar than opposite
#  100        Colors are exact opposite

threshold = 20
saturation = 10
check_contrast = true
fallback_generator="complementary"

[templates]
hypr.template = 'colors-hyprland.conf'
hypr.target = '~/.config/hypr/colors.conf'

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/colors.rasi'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors.css'

swaync.template = 'colors-swaync.css'
swaync.target = '~/.config/swaync/colors.css'

wal.template = 'colors-wal.json'
wal.target = "~/.cache/wal/colors.json"
