# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "wal"

# lab - labmixed - lch - lchmixed
color_space = "lch"

# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "dark16"

check_contrast = true

#saturation = 50


[templates]
emacs.target = '~/.cache/wal/colors.json'
emacs.template = 'colors-emacs.json'

foot.target = '~/.config/foot/colors.ini'
foot.template = 'colors-foot.ini'

hypr.target = '~/.config/hypr/colors-hyprland.conf'
hypr.template = 'colors-hyprland.conf'

hyprtoolkit.target = '~/.config/hypr/colors-toolkit.conf'
hyprtoolkit.template = 'colors-hyprtoolkit.conf'

kitty.target = '~/.config/kitty/colors.conf'
kitty.template = 'colors-kitty.conf'

rofi.target = '~/.config/rofi/colors.rasi'
rofi.template = 'colors-rofi.rasi'

swaync.target = '~/.config/swaync/colors.css'
swaync.template = 'colors-swaync.css'

waybar.target = '~/.config/waybar/colors.css'
waybar.template = 'colors-waybar.css'

wlogout.target = '~/.config/wlogout/style.css'
wlogout.template = 'colors-wlogout.css'
