alpha = 90

# How the image is parse, in order to get the colors:
#full
#        Read and return the whole image pixels more precision slower.
# resized
#        Resizes the image before parsing mantaining its aspect ratio.
# wal
#        Uses image magick convert to generate the colors like pywal.
# thumb
#        Faster algo hardcoded to x no ratio respected.
# fastresize
#        A much faster resize algo that uses SIMD. For some reason it  fails  on
#        some  images  where  resized doesn't for this reason it doesn't replace
#        but rather it s a new option.
# kmeans
#        Kmeans is an algo that divides and picks pixels all around  the  image.
#        Requires  more tweaking and more in depth testing but for the most part
#        it just werks.

backend = "kmeans"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed - labansi - lchansi

color_space = "labmixed"

# NOTE: All filters will fill 16 colors (from color0 to color15), 16 color
#       variations are the 'ilusion' of more colors by opaquing color1 to color5.
# Use the most prominent colors in a way that makes sense, a scheme:
#  * dark        - 8 dark colors, dark background and light contrast
#  * dark16      - Same as `dark` but uses the 16 colors trick
#  * harddark    - Same as `dark` with hard hue colors
#  * harddark16  - Harddark with 16 color variation
#  * light       - Light bg, dark fg
#  * light16     - Same as `light` but uses the 16 color trick
#  * softdark    - Variant of softlight, uses the lightest colors and a dark
#                   background (could be interpreted as `dark` inversed)
#  * softdark16  - softdark with 16 color variation
#  * softlight   - Light with soft pastel colors, counterpart of `harddark`
#  * softlight16 - softlight with 16 color variation

palette = "dark16"

# Difference between similar colors, used by the colorspace:
#  1          Not perceptible by human eyes.
#  1 - 2      Perceptible through close observation.
#  2 - 10     Perceptible at a glance.
#  11 - 49    Colors are more similar than opposite
#  100        Colors are exact opposite

threshold = 11

[templates]
hypr.template = 'colors-hyprland.conf'
hypr.target = '~/.config/hypr/colors.conf'

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/colors.rasi'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors.css'

swaync.template = 'colors-swaync.css'
swaync.target = '~/.config/swaync/colors.css'

wal.template = 'colors-wal.json'
wal.target = "~/.cache/wal/colors.json"
