#! /bin/sh

# Run sxhkd - used to handle keypress events
pgrep -x sxhkd > /dev/null || sxhkd &


# Setup number and names of monitors (desktops).
bspc monitor -d I II III IV V VI


# Configure gloabl settings
bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.52
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config automatic_scheme      longest_side
bspc config removal_adjustment    true
bspc config left_monocle_padding  180
bspc config right_monocle_padding 180
bspc config single_monocle        true



# To find the name (requires XDG name) use:
# xprop | grep WM_CLASS and then click on the window.
bspc rule -a Emacs state=tiled


# Keyboard/mouse/trackpad settings
setxkbmap -option ctrl:nocaps
xinput --set-prop "DELL08AF:00 06CB:76AF Touchpad" "libinput Natural Scrolling Enabled" 1
xinput --set-prop "DELL08AF:00 06CB:76AF Touchpad" "libinput Tapping Enabled" 1
xinput --set-prop "DELL08AF:00 06CB:76AF Touchpad" "libinput Tapping Drag Enabled" 1
xinput --set-prop "DELL08AF:00 06CB:76AF Touchpad" "libinput Middle Emulation Enabled" 1


# Helper apps (i.e. make this an actual desktop)
nitrogen --restore
picom -b --experimental-backends
light-locker &


# Panel, notifications and systray apps
polybar bar &
pa-applet &
blueman-applet & # in 'blueman' package
/usr/lib/xfce4/notifyd/xfce4-notifyd &
xfce4-power-manager
