#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a firefox desktop='^5'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore
picom -b
setxkbmap -option ctrl:nocaps
xinput --set-prop "DELL08AF:00 06CB:76AF Touchpad" "libinput Natural Scrolling Enabled" 1
xinput --set-prop "DELL08AF:00 06CB:76AF Touchpad" "libinput Tapping Enabled" 1
xinput --set-prop "DELL08AF:00 06CB:76AF Touchpad" "libinput Tapping Drag Enabled" 1
xinput --set-prop "DELL08AF:00 06CB:76AF Touchpad" "libinput Middle Emulation Enabled" 1

tint2 &
blueman-applet &
pa-applet &
cbatticon &
nm-applet &
albert &
