Net/ThemeName "deepin-dark"
Net/IconThemeName "kora"
Gtk/CursorThemeName "default"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
