[cursor]
blink_interval = 250
blink_timeout = 0
style = { shape = "Beam", blinking = "Always" }

[env]
TERM = "alacritty"

[font]
size = 13

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
y = 1

[[keyboard.bindings]]
chars = "\u001B[9;5u"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[44;5u"
key = "Comma"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[45;7u"
key = "Minus"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[61;7u"
key = "Equals"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[90;6u"
key = "Z"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
multiplier = 10

[window.padding]
x = 6
y = 6

[general]
live_config_reload = true


[window]
opacity = 0.85

[colors.primary]
background = "#131613"
foreground = "#c4c4c4"

[colors.cursor]
text = "#131613"
cursor = "#c4c4c4"

[colors.vi_mode_cursor]
text = "#131613"
cursor = "#c4c4c4"

[colors.search.matches]
foreground = "#131613"
background = "#c4c4c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5b705b"
background = "#c4c4c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#131613"
red = "#7A9A4A"
green = "#97B843"
yellow = "#98B155"
blue = "#ADD25C"
magenta = "#67728C"
cyan = "#79859D"
white = "#c4c4c4"

[colors.bright]
black = "#5b705b"
red = "#7A9A4A"
green = "#97B843"
yellow = "#98B155"
blue = "#ADD25C"
magenta = "#67728C"
cyan = "#79859D"
white = "#c4c4c4"

[colors.dim]
black = "#c4c4c4"
red = "#7A9A4A"
green = "#67728C"
yellow = "#98B155"
blue = "#ADD25C"
magenta = "#97B843"
cyan = "#79859D"
white = "#5b705b"
