[cursor]
blink_interval = 250
blink_timeout = 0
style = { shape = "Beam", blinking = "Always" }

[env]
TERM = "alacritty"

[font]
size = 13

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
y = 1

[[keyboard.bindings]]
chars = "\u001B[9;5u"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[44;5u"
key = "Comma"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[45;7u"
key = "Minus"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[61;7u"
key = "Equals"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[90;6u"
key = "Z"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
multiplier = 10

[window.padding]
x = 6
y = 6

[general]
live_config_reload = true


[window]
opacity = 0.85

[colors.primary]
background = "#253148"
foreground = "#c8cbd1"

[colors.cursor]
text = "#253148"
cursor = "#c8cbd1"

[colors.vi_mode_cursor]
text = "#253148"
cursor = "#c8cbd1"

[colors.search.matches]
foreground = "#253148"
background = "#c8cbd1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#707888"
background = "#c8cbd1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#253148"
red = "#9AB2E5"
green = "#A8BBE7"
yellow = "#B3C1DE"
blue = "#B9C8EB"
magenta = "#C6CCDD"
cyan = "#CBD6F2"
white = "#c8cbd1"

[colors.bright]
black = "#707888"
red = "#9AB2E5"
green = "#A8BBE7"
yellow = "#B3C1DE"
blue = "#B9C8EB"
magenta = "#C6CCDD"
cyan = "#CBD6F2"
white = "#c8cbd1"

[colors.dim]
black = "#c8cbd1"
red = "#9AB2E5"
green = "#C6CCDD"
yellow = "#B3C1DE"
blue = "#B9C8EB"
magenta = "#A8BBE7"
cyan = "#CBD6F2"
white = "#707888"
