[cursor]
blink_interval = 250
blink_timeout = 0
style = { shape = "Beam", blinking = "Always" }

[env]
TERM = "alacritty"

[font]
size = 13

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
y = 1

[[keyboard.bindings]]
chars = "\u001B[9;5u"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[44;5u"
key = "Comma"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[45;7u"
key = "Minus"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[61;7u"
key = "Equals"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[90;6u"
key = "Z"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
multiplier = 10

[window.padding]
x = 6
y = 6

[general]
live_config_reload = true


[window]
opacity = 0.80

[colors.primary]
background = "#0e1b0a"
foreground = "#c2c6c1"

[colors.cursor]
text = "#0e1b0a"
cursor = "#c2c6c1"

[colors.vi_mode_cursor]
text = "#0e1b0a"
cursor = "#c2c6c1"

[colors.search.matches]
foreground = "#0e1b0a"
background = "#c2c6c1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5f6e5a"
background = "#c2c6c1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0e1b0a"
red = "#B5DB60"
green = "#827D81"
yellow = "#979892"
blue = "#B2B1B2"
magenta = "#C4CEAD"
cyan = "#D4D3D3"
white = "#c2c6c1"

[colors.bright]
black = "#5f6e5a"
red = "#B5DB60"
green = "#827D81"
yellow = "#979892"
blue = "#B2B1B2"
magenta = "#C4CEAD"
cyan = "#D4D3D3"
white = "#c2c6c1"

[colors.dim]
black = "#c2c6c1"
red = "#B5DB60"
green = "#C4CEAD"
yellow = "#979892"
blue = "#B2B1B2"
magenta = "#827D81"
cyan = "#D4D3D3"
white = "#5f6e5a"
