[colors-dark]
blur=true
alpha = {{ colors.background.default.alpha }}
background = {{ colors.background.default.hex_stripped }}
foreground = {{ colors.on_surface.default.hex_stripped }}

# Normal/regular colors (color palette 0-7)
regular0={{ base16.base00.default.hex_stripped }}  # black
regular1={{ base16.base01.default.hex_stripped }}  # red
regular2={{ base16.base02.default.hex_stripped }}  # green
regular3={{ base16.base03.default.hex_stripped }}  # yellow
regular4={{ base16.base04.default.hex_stripped }}  # blue
regular5={{ base16.base05.default.hex_stripped }}  # magenta
regular6={{ base16.base06.default.hex_stripped }}  # cyan
regular7={{ base16.base07.default.hex_stripped }}  # white

# Bright colors (color palette 8-15)
bright0={{ base16.base08.default.hex_stripped }}   # bright black
bright1={{ base16.base09.default.hex_stripped }}   # bright red
bright2={{ base16.base0a.default.hex_stripped }}   # bright green
bright3={{ base16.base0b.default.hex_stripped }}   # bright yellow
bright4={{ base16.base0c.default.hex_stripped }}   # bright blue
bright5={{ base16.base0d.default.hex_stripped }}   # bright magenta
bright6={{ base16.base0e.default.hex_stripped }}   # bright cyan
bright7={{ base16.base0f.default.hex_stripped }}   # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>
